version: "3.8"

services:
  whaticket_backend:
    image: whaticket-backend:latest
    volumes:
      - whaticket_backend_data:/usr/src/app/
    environment:
      # POSTGRES
      - DB_DIALECT=postgres
      - DB_HOST=postgres_whaticket
      - DB_PORT=5432
      - DB_USER=usuario_postgres # Informe o usuário do seu banco
      - DB_PASS=senha_postgres # Informe a senha do seu banco
      - DB_NAME=nome_do_banco # Informe o nome do seu banco
      - TZ=America/Sao_Paulo

      # BACKEND
      - JWT_SECRET=seu_segredo_jwt # Defina um segredo forte
      - JWT_REFRESH_SECRET=seu_refresh_segredo_jwt # Defina um segredo forte
      - PORT=3000
      - PROXY_PORT=443
      - BACKEND_URL=https://api.suaempresa.com.br # Informe a URL pública do backend
      - FRONTEND_URL=https://app.suaempresa.com.br # Informe a URL pública do frontend
      - CHROME_ARGS=--no-sandbox --disable-setuid-sandbox

      # REDIS
      - REDIS_URI=redis://:senha_redis@whaticket_redis:6379 # Informe a senha do Redis
      - REDIS_OPT_LIMITER_MAX=1
      - REDIS_OPT_LIMITER_DURATION=3000

      # GERENCIANET (opcional, para pagamentos)
      - GERENCIANET_SANDBOX=false
      - GERENCIANET_CLIENT_ID=seu_client_id_gerencianet
      - GERENCIANET_CLIENT_SECRET=seu_client_secret_gerencianet
      - GERENCIANET_PIX_CERT=seu_certificado_pix
      - GERENCIANET_PIX_KEY=sua_chave_pix

      # LIMITES DE USUÁRIOS E CONEXÕES
      - USER_LIMIT=10000
      - CONNECTIONS_LIMIT=100000
      - CLOSED_SEND_BY_ME=true

      # E-MAIL
      - MAIL_HOST=smtp.seuprovedor.com # Informe o host SMTP
      - MAIL_USER=seu_email@seudominio.com # Informe o e-mail de envio
      - MAIL_PASS=senha_email # Informe a senha do e-mail
      - MAIL_FROM=Whaticket <seu_email@seudominio.com> # Informe o remetente
      - MAIL_PORT=587 # Informe a porta SMTP
    networks:
      - whaticket
      - traefik_public # Informe sua rede pública do traefik
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public" # rede do traefik, ou traefik.swarm.network=traefik_public
        - "traefik.http.routers.whaticket_backend.rule=Host(`api.suaempresa.com.br`)"
        - "traefik.http.routers.whaticket_backend.entrypoints=websecure"
        - "traefik.http.routers.whaticket_backend.tls.certresolver=leresolver"
        - "traefik.http.routers.whaticket_backend.service=whaticket_backend"
        - "traefik.http.services.whaticket_backend.loadbalancer.server.port=3000"
        - "traefik.http.middlewares.cors_backend.headers.accessControlAllowOriginList=https://app.suaempresa.com.br"
        - "traefik.http.middlewares.cors_backend.headers.accessControlAllowMethods=GET,HEAD,PUT,PATCH,POST,DELETE"
        - "traefik.http.middlewares.cors_backend.headers.accessControlAllowHeaders=Origin, X-Requested-With, Content-Type, Accept, Authorization"
        - "traefik.http.middlewares.cors_backend.headers.accessControlAllowCredentials=true"
        - "traefik.http.middlewares.backend_headers.headers.customResponseHeaders.X-Frame-Options=SAMEORIGIN"
        - "traefik.http.middlewares.backend_headers.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
        - "traefik.http.middlewares.backend_headers.headers.customResponseHeaders.X-XSS-Protection=1; mode=block"
        - "traefik.http.middlewares.backend_headers.headers.customResponseHeaders.Strict-Transport-Security=max-age=31536000; includeSubdomains;"
        - "traefik.http.middlewares.backend_headers.headers.customResponseHeaders.Referrer-Policy=no-referrer-when-downgrade"
        - "traefik.http.middlewares.backend_headers.headers.customResponseHeaders.Cache-Control=no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
        - "traefik.http.middlewares.backend_compress.compress=true"
        - "traefik.http.middlewares.backend_body_size.buffering.maxRequestBodyBytes=20971520"
        - "traefik.http.routers.whaticket_backend.middlewares=cors_backend,backend_headers,backend_compress,backend_body_size"

  whaticket_frontend:
    image: whaticket-frontend:latest
    volumes:
      - whaticket_frontend_data:/usr/src/app/
    environment:
      - REACT_APP_BACKEND_URL=https://api.suaempresa.com.br # Informe a URL pública do backend
      - REACT_APP_HOURS_CLOSE_TICKETS_AUTO=24
    ports:
      - "3250:3250"
    networks:
      - whaticket
      - traefik_public # Informe sua rede pública do traefik
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public" # rede do traefik, traefik.swarm.network=traefik_public
        - "traefik.http.routers.whaticket_frontend.rule=Host(`app.suaempresa.com.br`)"
        - "traefik.http.routers.whaticket_frontend.entrypoints=websecure"
        - "traefik.http.routers.whaticket_frontend.tls.certresolver=leresolver"
        - "traefik.http.routers.whaticket_frontend.service=whaticket_frontend"
        - "traefik.http.services.whaticket_frontend.loadbalancer.server.port=3250"
        - "traefik.http.middlewares.frontend_headers.headers.customResponseHeaders.X-Frame-Options=SAMEORIGIN"
        - "traefik.http.middlewares.frontend_headers.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
        - "traefik.http.middlewares.frontend_headers.headers.customResponseHeaders.X-XSS-Protection=1; mode=block"
        - "traefik.http.middlewares.frontend_headers.headers.customResponseHeaders.Strict-Transport-Security=max-age=31536000; includeSubdomains;"
        - "traefik.http.middlewares.frontend_headers.headers.customResponseHeaders.Referrer-Policy=no-referrer-when-downgrade"
        - "traefik.http.middlewares.frontend_headers.headers.customResponseHeaders.Cache-Control=no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
        - "traefik.http.middlewares.frontend_compress.compress=true"
        - "traefik.http.middlewares.frontend_body_size.buffering.maxRequestBodyBytes=20971520"
        - "traefik.http.routers.whaticket_frontend.middlewares=frontend_headers,frontend_compress,frontend_body_size"

  postgres_whaticket:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nome_do_banco # Informe o nome do seu banco
      - POSTGRES_USER=usuario_postgres # Informe o usuário do seu banco
      - POSTGRES_PASSWORD=senha_postgres # Informe a senha do seu banco
      - TZ=America/Sao_Paulo
    networks:
      - whaticket
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

  whaticket_redis:
    image: redis:latest
    command: redis-server --requirepass "senha_redis" # Informe a senha do Redis
    volumes:
      - redis-data:/data
    networks:
      - whaticket
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

networks:
  whaticket:
    driver: overlay
  traefik_public:
    external: true

volumes:
  whaticket_backend_data:
  whaticket_frontend_data:
  postgres-data:
  redis-data:
